### ISSUE TITLE
Update menu items in Home Page

### ISSUE THREAD

**Issue by fferz** [sitewhere/community-documentation#13] opened 2021-03-03 12:59 UTC

**Comment by derekadams** [comment] 2021-03-03 14:28
I think this is a duplicate of https://github.com/sitewhere/community-documentation/issues/12

**Comment by fferz** [comment] 2021-03-03 19:27
I updated the menu and I added the dropdown for the Community section, but now the templates are lost :(
![imagen](https://user-images.githubusercontent.com/3790709/109860786-52447700-7c3d-11eb-9005-bdf48524a9fd.png)

**Comment by derekadams** [comment] 2021-03-03 20:05
We would need to have two separate navigation bar layouts, one for the community menus, and a second for the homepage menu. I think you can use the Hugo frontmatter to choose which navigation bar is displayed so that you can override the home page navigation.

**Comment by fferz** [comment] 2021-03-04 12:18
I asked Fabri for help

**Comment by jorgevillaverde-sitewhere** [comment] 2021-03-04 15:29
![image](https://user-images.githubusercontent.com/39090513/109987236-35637e80-7ce5-11eb-9838-995e6b095905.png)
![image](https://user-images.githubusercontent.com/39090513/109987330-4b713f00-7ce5-11eb-8c01-a336414386e8.png)

**Closed as completed** 2021-03-04 15:45 UTC
Labels: duplicate
